---

- name: Install packages to allow apt to use https
  apt: update_cache=yes name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add apt repository key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install Docker
  apt: update_cache=yes name=docker-ce state=latest
