apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{ kube_master_ip }}:6443"
    token: "{{ kubeadm_token }}"
    unsafeSkipCAVerification: true
nodeRegistration:
  name: "{{ ansible_hostname }}"
  kubeletExtraArgs:
    node-ip: "{{ host_ip }}"
    runtime-cgroups: /systemd/system.slice
    kubelet-cgroups: /systemd/system.slice
{% if kubelet_extra_args -%}
{{ kubelet_extra_args | to_nice_yaml(indent=2) | indent(4, true) }}
{% endif -%}
