apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
# Make sure to advertise the API on the correct IP
apiEndpoint:
  advertiseAddress: "{{ host_ip }}"
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: "{{ kubeadm_token }}"
    ttl: "0"
    usages:
      - signing
      - authentication
nodeRegistration:
  name: "{{ ansible_hostname }}"
  kubeletExtraArgs:
    node-ip: "{{ host_ip }}"
    runtime-cgroups: /systemd/system.slice
    kubelet-cgroups: /systemd/system.slice
{% if kubelet_extra_args -%}
{{ kubelet_extra_args | to_nice_yaml(indent=2) | indent(4, true) }}
{% endif -%}
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
clusterName: "{{ cluster_name }}"
# Use the required Kubernetes version
kubernetesVersion: "{{ kubernetes_version_target }}"
{% if cluster_config_extra -%}
{{ cluster_config_extra | to_nice_yaml(indent=2) }}
{% endif -%}
