---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Setting this in a separate play is the only way to avoid a recursive templating error
- hosts: openstack
  tasks:
    - set_fact:
        cluster_name_bastion: "{{ cluster_name }}-bastion"

# Provision a separate stack for the bastion
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      vars:
        cluster_name: "{{ cluster_name_bastion }}"
        cluster_groups:
          - "{{ bastion_group }}"

# Provision the cluster infrastructure
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      vars:
        cluster_groups:
          - "{{ masters_group }}"
          - "{{ workers_group }}"

# Do the configuration
- import_playbook: cluster_configure.yml
  vars:
    cloud_provider: openstack

# Delete the bastion
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      vars:
        cluster_name: "{{ cluster_name_bastion }}"
        cluster_groups:
          - "{{ bastion_group }}"
        cluster_state: absent
