---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Provision infrastructure
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      vars:
        cluster_groups:
          - "{{ bastion_group }}"
          - "{{ masters_group }}"
          - "{{ workers_group }}"

# Do the configuration
- import_playbook: cluster_configure.yml
  vars:
    cloud_provider: openstack

# Scale the bastion group down to zero hosts
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      vars:
        stack_update_only: true
        cluster_groups:
          - "{{ bastion_group | combine({ 'num_nodes': 0 }) }}"
          - "{{ masters_group }}"
          - "{{ workers_group }}"
