---

# Do cluster setup for all hosts
- hosts: kube_masters,kube_workers
  remote_user: root
  any_errors_fatal: true
  roles:
    - kubeadm

# Install addons via the master
- hosts: kube_masters
  remote_user: root
  any_errors_fatal: true
  roles:
    - helm
    - ingress_nginx
