---
- hosts: openstack
  tasks:
    - block:
      - name: Get openstack_project_id when not defined
        command: "openstack project show {{ lookup('env', 'OS_PROJECT_NAME') }} -f value -c id"
        register: result
        when: not lookup('env', 'OS_PROJECT_ID')
      - debug: var=result
        failed_when:
          - result.stderr is not defined
          - result.stdout is not defined
          - result.stderr_lines | length > 0
          - result.stdout_lines | length == 1
      - name: Set openstack_project_id as fact
        set_fact:
          openstack_project_id: "{{ result.stdout_lines[0] | default(lookup('env', 'OS_PROJECT_ID')) }}"
      when: openstack_project_id is not defined
    - block:
      - name: Get openstack_user_id when not defined
        command: "openstack token issue -c user_id -f value"
        register: result
        failed_when:
          - result.stderr is not defined
          - result.stdout is not defined
          - result.stderr_lines | length > 0
          - result.stdout_lines | length != 1
        when: not lookup('env', 'OS_USER_ID')
      - name: Set openstack_user_id as fact
        set_fact:
          openstack_user_id: "{{ result.stdout_lines[0] | default(lookup('env', 'OS_USER_ID')) }}"
      when: openstack_user_id is not defined
    - block:
      - name: Get openstack_trust_id
        command: "openstack trust create {{ openstack_user_id }} {{ openstack_trustee_id }} --project {{ openstack_project_id }} --role={{ openstack_role_id }} -c id -f value"
        register: result
        failed_when:
          - result.stderr is not defined
          - result.stdout is not defined
          - result.stderr_lines | length > 0
          - result.stdout_lines | length != 1
        when: not lookup('env', 'OS_TRUST_ID')
      - name: Set openstack_trust_id as fact
        set_fact:
          openstack_trust_id: "{{ result.stdout_lines[0] | default(lookup('env', 'OS_TRUST_ID')) }}"
      when: openstack_trust_id is not defined
    - debug: var=groupvars
    - debug: var=hostvars
...
