---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Provision infrastructure with the correct groups using the jasmin.cluster-infra role
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      vars:
        cluster_groups:
          - name: kube_masters
            num_nodes: 1
            flavor: "{{ master_flavor | default('j3.medium') }}"
            root_volume_size: "{{ root_volume_size | default(20) }}"
          - name: kube_workers
            num_nodes: "{{ num_workers }}"
            flavor: "{{ worker_flavor | default('j3.medium') }}"
            root_volume_size: "{{ root_volume_size | default(20) }}"

# Do the configuration
- import_playbook: cluster_configure.yml
  vars:
    cloud_provider: openstack
