---

- hosts: all
  remote_user: root
  force_handlers: yes
  roles:
    - role: setup_networking
      when: setup_networking is defined and setup_networking
    - role: setup_storage
      when: setup_storage is defined and setup_storage

- hosts: kube_hosts
  remote_user: root
  force_handlers: yes
  roles:
    - docker_ce
    - kubernetes
    - role: storage_rook
      when: storage_rook is not defined or storage_rook
    - role: ingress_nginx
      when: inventory_hostname in groups['kube_masters']
    - role: helm
      when:
        - inventory_hostname in groups['kube_masters']
        - install_helm is not defined or install_helm
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- hosts: proxy_hosts
  remote_user: root
  force_handlers: yes
  roles:
    - proxy_passthru
