---
#####
## Performs Kubernetes cluster configuration for any inventory that defines
## the groups "kube_masters" and "kube_workers"
#####

# Do cluster setup for all hosts
- hosts: cluster
  remote_user: root
  any_errors_fatal: true
  roles:
    - kubeadm

# Install addons via the master
- hosts: kube_masters
  remote_user: root
  any_errors_fatal: true
  roles:
    - helm
    - ingress_nginx
#    - kubernetes_dashboard
