---
- hosts: openstack
  tasks:
    - block:
        - name: Authenticate to the cloud and retrieve current project_id, user_id and auth_token
          os_keystone_trust:
            trustee_user_id: "{{ openstack_trustee_id }}"
            impersonation: true
            roles:
              - name: "{{ openstack_role }}"
        - name: Set openstack_project_id, openstack_user_id and opestack_trust_id as fact
          set_fact:
            openstack_project_id: "{{ project_id | default(lookup('env', 'OS_PROJECT_ID')) }}"
            openstack_user_id: "{{ user_id | default(lookup('env', 'OS_USER_ID')) }}"
            openstack_trust_id: "{{ trust_id | default(lookup('env', 'OS_TRUST_ID')) }}"
      when:
        (openstack_trust_id is not defined or
        openstack_project_id is not defined or
        openstack_user_id is not defined)
...
