---
#####
## Playbook that provisions and then configures a Kubernetes
## cluster on OpenStack
#####

# Provision infrastructure with the correct groups using the jasmin.cluster-infra role
- hosts: openstack
  roles:
    - role: jasmin.cluster-infra
      vars:
        cluster_gw_group: kube-masters
        cluster_groups:
          - name: kube-masters
            user: root
            node_resource: "Cluster::Node"
            nodenet_resource: "Cluster::NodeNet1WithPreallocatedFIP"
            nodenet_fips:
              - uuid: "{{ fip_uuid }}"
                ip: "{{ fip_ip }}"
            num_nodes: 1
            flavor: "{{ master_flavor | default('j4.small') }}"
            root_volume_size: "{{ root_volume_size | default(20) }}"
          - name: kube-workers
            user: root
            node_resource: "Cluster::Node"
            nodenet_resource: "Cluster::NodeNet1"
            num_nodes: "{{ num_workers }}"
            flavor: "{{ worker_flavor | default('j4.small') }}"
            root_volume_size: "{{ root_volume_size | default(20) }}"

# Do the configuration
- import_playbook: cluster_configure.yml
#  vars:
#    cloud_provider: openstack
