---

- hosts: kube_hosts
  roles:
    - kubeadm
    - role: helm
      when: inventory_hostname in groups['kube_masters']
    - role: ingress_nginx
      when: inventory_hostname in groups['kube_masters']
    - storage_rook
    - role: kubernetes_dashboard
      when: inventory_hostname in groups['kube_masters']
