---

- name: Generate new kubeadm token
  command: kubeadm token generate
  register: kubeadm_token_generate
  when: kubeadm_token is not defined

- name: Set kubeadm_token fact
  set_fact:
    kubeadm_token: "{{ kubeadm_token_generate.stdout }}"
  when: kubeadm_token is not defined

# Set the token TTL so that the token doesn't expire
# Use the IP address as the node name
- name: Initialise Kubernetes master
  command: >
    kubeadm init
      --token={{ kubeadm_token }}
      --token-ttl=0
      --apiserver-advertise-address={{ host_ip }}
      --node-name={{ host_ip }}
      --ignore-preflight-errors=cri

- name: Update proxy-mode for kube-proxy
  shell: >
    kubectl -n kube-system get ds -l k8s-app=kube-proxy -o json |
      jq '.items[0].spec.template.spec.containers[0].command |= .+ ["--proxy-mode=userspace"]' |
      kubectl apply -f - &&
    kubectl -n kube-system delete pods -l k8s-app=kube-proxy
  when: userspace_proxy

- name: Install pod network
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Ensure kube-dns has started
  command: kubectl -n kube-system rollout status deployment kube-dns
