---

- name: Get kubeadm token from master
  shell: >
    set -o pipefail ;
    kubeadm token list | head -n 2 | tail -n 1 | awk '{ print $1 };'
  register: kubeadm_token
  delegate_to: "{{ groups['kube_masters'][0] }}"

- name: Join Kubernetes cluster
  command: >
    kubeadm join
      --token={{ kubeadm_token.stdout }}
      --ignore-preflight-errors=cri
      --node-name={{ host_ip }}
      --discovery-token-unsafe-skip-ca-verification
      {{ kube_master_ip }}:6443

- name: Wait for node to become ready
  shell: kubectl wait --for condition=ready --timeout -1s node {{ host_ip }}
  delegate_to: "{{ groups['kube_masters'][0] }}"
