---

- name: Join Kubernetes cluster
  command: >
    kubeadm join
      --token={{ kubeadm_token }}
      --ignore-preflight-errors=cri
      --node-name={{ host_ip }}
      --discovery-token-unsafe-skip-ca-verification
      {{ kube_master_ip }}:6443

- name: Wait for node to become ready (max 5 minutes)
  shell: kubectl wait --for condition=ready --timeout 300s node {{ host_ip }}
