---

- name: Install Docker
  yum:
    name: docker
    state: latest

- name: Ensure Docker is started
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Kubernetes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "kubelet-{{ kubernetes_version_target }}"
    - "kubeadm-{{ kubernetes_version_target }}"
    - "kubectl-{{ kubernetes_version_target }}"

# Make sure the kubelet uses the IP address as the hostname
- name: Update kubelet hostname-override
  copy:
    dest: /etc/systemd/system/kubelet.service.d/09-hostname-override.conf
    content: |
      [Service]
      Environment="KUBELET_EXTRA_ARGS=--hostname-override={{ host_ip }}"

- name: Ensure kubelet is started
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Configure master
  include_tasks: "configure-master.yml"
  when: inventory_hostname in groups['kube_masters']

- name: Configure minions
  include_tasks: "configure-minion.yml"
  when: inventory_hostname in groups['kube_minions']

- name: Set installed Kubernetes version fact
  set_fact:
    kubernetes_version_installed: "{{ kubernetes_version_target }}"
