---

- name: Upgrade kubeadm
  yum:
    name: kubeadm-{{ kubernetes_version }}
    state: latest

- name: Fetch available control plane upgrades
  command: kubeadm upgrade plan
  when: inventory_hostname in groups['kube_masters']

- name: Upgrade control plane to desired version
  command: kubeadm upgrade apply -y v{{ kubernetes_version }}
  when: inventory_hostname in groups['kube_masters']

- name: Upgrade kubectl
  yum:
    name: kubectl-{{ kubernetes_version }}
    state: latest

- name: Upgrade pod network
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when: inventory_hostname in groups['kube_masters']

- name: Get group of hosts requiring upgrade
  group_by:
    key: kube_upgrade

- name: Upgrade node packages (one node at a time)
  include_role:
    name: kubeadm
    tasks_from: "upgrade-packages.yml"
  with_items: "{{ groups['kube_upgrade'] }}"
  when: inventory_hostname in groups['kube_masters']