---

- name: Drain node
  command: kubectl drain {{ host_ip }} --ignore-daemonsets
  delegate_to: "{{ groups['kube_masters'][0] }}"

- name: Upgrade docker and kubernetes packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker
    - kubelet-{{ kubernetes_version_target }}
    - kubeadm-{{ kubernetes_version_target }}
    - kubectl-{{ kubernetes_version_target }}

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Restart docker and kubelet
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - docker
    - kubelet

- name: Uncordon node
  command: kubectl uncordon {{ host_ip }}
  delegate_to: "{{ groups['kube_masters'][0] }}"
