---

- name: Upgrade kubeadm and kubectl
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kubeadm-{{ kubernetes_version_target }}
    - kubectl-{{ kubernetes_version_target }}
  register: kubeadm_kubectl_upgraded

# If kubectl was upgraded, upgrade the control plane
- name: Upgrade control plane
  block:
    - name: Upgrade control plane to desired version
      command: kubeadm upgrade apply -y v{{ kubernetes_version_target }}

    - name: Upgrade pod network
      shell: |
        set -eo pipefail
        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  when:
    - kube_role == "master"
    - kubeadm_kubectl_upgraded is changed

# Try our best to drain pods from the host - if the drain times out, continue anyway
- name: Drain pods from host
  command: kubectl drain {{ ansible_hostname }} --ignore-daemonsets --timeout={{ kubectl_drain_timeout }}
  delegate_to: "{{ kube_master_inventory_hostname }}"
  register: kubectl_drain
  failed_when: kubectl_drain.rc != 0 and 'did not complete within' not in kubectl_drain.stderr

- include_tasks: prerequisites.yml

## NOTE: docker will be upgraded as part of the general package upgrade if an update is available

- name: Upgrade kubelet
  yum:
    name: kubelet
    state: latest
  register: kubelet_upgraded

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Upgrade kubelet config
  command: kubeadm upgrade node config --kubelet-version v{{ kubernetes_version_target }}
  when:
    - kube_role == "worker"
    - kubelet_upgraded is changed

- name: Override kubelet arguments
  copy:
    dest: /etc/sysconfig/kubelet
    content: |
      KUBELET_EXTRA_ARGS="--node-ip={{ host_ip }} --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice"
  when: kubelet_upgraded is changed

- name: Restart docker and kubelet
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - docker
    - kubelet
  when: kubelet_upgraded is changed

- name: Wait for API server to become available after restart (max 5 mins)
  command: kubectl version --request-timeout=1s
  register: api_server_available
  until: api_server_available is succeeded
  retries: 60
  delay: 5
  when: kube_role == "master"

- name: Uncordon host
  command: kubectl uncordon {{ ansible_hostname }}
  delegate_to: "{{ kube_master_inventory_hostname }}"

- name: Set installed Kubernetes version fact
  set_fact:
    kubernetes_version_installed: "{{ kubernetes_version_target }}"
