---

- name: Drain pods from node {{ item }}
  # Allow 60s for the node to drain
  command: kubectl drain {{ item }} --ignore-daemonsets

- name: Upgrade docker and kubelet on node {{ item }}
  yum:
    name: "{{ package }}"
    state: latest
  with_items:
    - docker
    - kubelet-{{ kubernetes_version }}
  loop_control:
    loop_var: package
  delegate_to: "{{ item }}"

- name: Reload systemd daemon on node {{ item }}
  systemd:
    daemon_reload: yes
  delegate_to: "{{ item }}"

- name: Restart kubelet on node {{ item }}
  service:
    name: kubelet
    state: restarted
  delegate_to: "{{ item }}"

- name: Uncordon node {{ item }}
  command: kubectl uncordon {{ item }}
  