---

- include: extend_lvmvg.yml
  with_items: "{{ storage_devices }}"
  loop_control:
    loop_var: storage_device

- name: Extend LVM root volume to fill volume group
  command: lvextend -l +100%FREE /dev/{{ root_volume_group }}/{{ root_volume_name }}
  register: lvextend
  changed_when: lvextend.rc == 0
  failed_when: lvextend.rc != 0 and 'matches existing size' not in lvextend.stderr

- name: Resize root filesystem to fill volume (Ubuntu)
  command: resize2fs /dev/{{ root_volume_group }}/{{ root_volume_name }}
  when: ansible_distribution == 'Ubuntu'

- name: Resize root filesystem to fill volume (CentOS)
  command: xfs_growfs /dev/{{ root_volume_group }}/{{ root_volume_name }}
  when: ansible_distribution == 'CentOS'
