---

- block:
    - name: Ensure manifests directory exists
      file:
        path: /root/manifests
        state: directory

    - name: Install Cinder storage class manifest
      template:
        src: templates/openstack/cinder-storageclass.yaml
        dest: /root/manifests/openstack-cinder-storageclass.yaml

    - name: Install Cinder storage class
      command: kubectl apply -f /root/manifests/openstack-cinder-storageclass.yaml

    - name: Create TLS keypair for k8s-keystone-auth
      command: >
        openssl req -x509 -new -nodes -days 3650
          -subj "/CN=k8s-keystone-auth"
          -keyout /etc/kubernetes/pki/k8s-keystone-auth.key
          -out /etc/kubernetes/pki/k8s-keystone-auth.crt
      args:
        creates: /etc/kubernetes/pki/k8s-keystone-auth.crt

    - name: Create Kubernetes secret for TLS keypair
      shell: |
        set -eo pipefail
        kubectl -n kube-system create secret generic k8s-keystone-auth-tls  \
          --from-file=tls.crt=/etc/kubernetes/pki/k8s-keystone-auth.crt  \
          --from-file=tls.key=/etc/kubernetes/pki/k8s-keystone-auth.key  \
          --dry-run -o yaml |  \
        kubectl apply -f -

    - name: Install k8s-keystone-auth manifest
      template:
        src: templates/openstack/k8s-keystone-auth-deployment.yaml
        dest: /root/manifests/openstack-k8s-keystone-auth-deployment.yaml

    - name: Create/update k8s-keystone-auth deployment
      command: kubectl apply -f /root/manifests/openstack-k8s-keystone-auth-deployment.yaml

    - name: Ensure k8s-keystone-auth rolls out successfully
      command: kubectl -n kube-system rollout status deployment k8s-keystone-auth

    # Kubernetes apiserver doesn't support cluster DNS, so replace the DNS name with
    # the allocated ClusterIP for the service
    - name: Get ClusterIP for k8s-keystone-auth
      command: kubectl -n kube-system get svc k8s-keystone-auth -o jsonpath='{.spec.clusterIP}'
      register: k8s_keystone_auth_ip

    - name: Patch k8s-keystone-auth webhook config with ClusterIP
      replace:
        path: /etc/kubernetes/k8s-keystone-auth-webhook-config.yaml
        regexp: "k8s-keystone-auth\.kube-system"
        replace: "{{ k8s_keystone_auth_ip.stdout }}"
  when: kube_role == "master"
