---

- name: Ensure manifests directory exists
  file:
    path: /root/manifests
    state: directory

- name: Install Cinder storage class manifest
  template:
    src: templates/openstack/cinder-storageclass.yaml
    dest: /root/manifests/openstack-cinder-storageclass.yaml

- name: Install Cinder storage class
  command: kubectl apply -f /root/manifests/openstack-cinder-storageclass.yaml
