---

- name: Update Helm repositories
  command: helm repo update

- name: Ensure helm values directory exists
  file:
    path: /root/helm/ingress_nginx
    state: directory

- name: Copy Helm values to host
  copy:
    src: files/helm-values.yaml
    dest: /root/helm/ingress_nginx/values.yaml

- name: Install/upgrade Nginx ingress controller
  command: >
    helm upgrade nginx-ingress stable/nginx-ingress
      --install
      --namespace nginx-ingress
      --values /root/helm/ingress_nginx/values.yaml

- name: Ensure Nginx ingress controller has started
  command: kubectl -n nginx-ingress rollout status deployment nginx-ingress-controller

- name: Allow external HTTP(S) traffic
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
