---

- name: Update Helm repositories
  command: helm repo update

- name: Create tempfile for Helm values
  tempfile:
    state: file
  register: ingress_values_file

- name: Copy Helm values to tempfile
  copy:
    src: files/helm-values.yaml
    dest: "{{ ingress_values_file.path }}"

- name: Install/upgrade Nginx ingress controller
  command: >
    helm upgrade nginx-ingress stable/nginx-ingress
      --install
      --namespace nginx-ingress
      --values {{ ingress_values_file.path }}

- name: Ensure Nginx ingress controller has started
  command: kubectl -n nginx-ingress rollout status deployment nginx-ingress-controller

- name: Allow external HTTP(S) traffic
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - http
    - https
