---

- name: Check if Helm is installed
  command: which helm
  register: helm_installed
  changed_when: false
  ignore_errors: yes

- name: Install Helm if not present
  import_role:
    name: helm
  when: helm_installed is failed

- name: Update Helm repositories
  command: helm repo update

# We use a daemonset on the host network
# Make sure to use the RollingUpdate update strategy
# The proxy can then load-balance port 80/443 across all cluster nodes
- name: Install Nginx ingress controller using Helm
  command: >
    helm upgrade nginx-ingress stable/nginx-ingress
      --install
      --namespace=nginx-ingress
      --set rbac.create=true
      --set serviceAccount.create=true
      --set controller.kind=DaemonSet
      --set controller.updateStrategy.type=RollingUpdate
      --set controller.hostNetwork=true
      --set controller.service.type=ClusterIP

- name: Ensure Nginx ingress controller has started
  command: kubectl -n nginx-ingress rollout status daemonset nginx-ingress-controller
