# This is the IPv4 address of the node
# If not given, use the default IPv4 address for the node
host_ip: "{{ ansible_default_ipv4.address }}"

# The default Kubernetes version
kubernetes_version: "1.10"

# By default, use the iptables proxy
userspace_proxy: false
