epel_preinstalled: false

# By default, use the IP of the default interface to advertise the Kubernetes master
kube_master_ip: "{{ hostvars[groups['kube_masters'][0]].ansible_default_ipv4.address }}"

# If true, switch proxy mode from iptables to userspace
use_userspace_proxy: false
