# The default Kubernetes version
kubernetes_version: "1.12"

# By default, use the default interface for cluster communication
cluster_interface: "{{ ansible_default_ipv4.interface }}"

# Find the IPv4 info for the current inventory host from hostvars for the cluster_interface
cluster_iface_ipv4: "{{ hostvars[inventory_hostname]['ansible_' + cluster_interface].ipv4 }}"

# This is the IPv4 address of the current inventory host
# By default, use the IPv4 address of the cluster_interface
host_ip: "{{ cluster_iface_ipv4.address }}"

# This is the CIDR of the cluster network
# By default, use the network and netmask of the cluster_interface
cluster_cidr: "{{ [cluster_iface_ipv4.network, cluster_iface_ipv4.netmask] | join('/') | ipaddr('net') }}"

# The inventory hostname of the master node
kube_master_inventory_hostname: "{{ groups['kube-masters'][0] }}"

# The IP address on the cluster interfaace of the master node
kube_master_ip: "{{ hostvars[kube_master_inventory_hostname]['ansible_' + cluster_interface].ipv4.address }}"

# The timeout to allow nodes to drain before continuing regardless
kubectl_drain_timeout: "300s"

# Only run upgrades if explicitly asked to
upgrade_packages: no
upgrade_kubernetes: no

# By default, take the OpenStack variables from the environment vars
openstack_auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
openstack_domain_name: "{{ lookup('env', 'OS_DOMAIN_NAME') }}"
openstack_project_id: "{{ lookup('env', 'OS_PROJECT_ID') }}"
openstack_username: "{{ lookup('env', 'OS_USERNAME') }}"
openstack_password: "{{ lookup('env', 'OS_PASSWORD') }}"
