---

- name: Ensure SELinux is disabled
  selinux:
    state: disabled

- name: Add yum repository for Kubernetes
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: >
      https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install Kubernetes
  yum: update_cache=yes name={{ item }} state=latest
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Ensure kubelet is started
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Enable EPEL
  yum: name=epel-release state=latest

- name: Install jq
  yum: name=jq state=latest
  when: inventory_hostname in groups['kube_masters']
