---

# The rbd kernel module needs to be enabled on every node that might want to mount storage
- name: Enable kernel module
  include_tasks: "kernel_module.yml"
  when: inventory_hostname in groups['kube-workers']

- name: Configure storage nodes
  include_tasks: "configure_storage.yml"
  when: inventory_hostname in groups['kube-workers']

- name: Install rook
  include_tasks: "install_rook.yml"
  when: inventory_hostname in groups['kube-masters']
