---

- name: Set storage label on storage nodes (attract storage pods to nodes)
  command: kubectl label --overwrite nodes {{ item }} "{{ storage_label.key }}={{ storage_label.value }}"
  with_items: "{{ storage_nodes }}"

- name: Set storage infrastructure taint (repel other pods from nodes)
  command: kubectl taint --overwrite nodes {{ item }} "{{ storage_taint.key }}={{ storage_taint.value }}:{{ storage_taint.effect }}"
  with_items: "{{ storage_nodes }}"
  when: apply_storage_taint

- name: Install rook repository
  command: helm repo add rook https://charts.rook.io/master

- name: Update Helm repositories
  command: helm repo update

- name: Get rook version
  shell: >
    set -o pipefail ; 
    helm search rook-ceph | tail -n 1 | awk '{ print $2; }'
  register: rook_version

- name: Create tempfile for Helm values
  tempfile:
    state: file
  register: rook_values_file

- name: Copy Helm values to tempfile
  template:
    src: helm-values.yaml
    dest: "{{ rook_values_file.path }}"

- name: Install/upgrade rook operator
  command: >
    helm upgrade rook-ceph-operator rook/rook-ceph
      --install
      --version {{ rook_version.stdout }}
      --namespace rook-system
      --values {{ rook_values_file.path }}

- name: Ensure rook operator has started
  command: kubectl -n rook-system rollout status deployment rook-ceph-operator

- name: Wait for rook agent daemonset to exist
  command: kubectl -n rook-system get daemonset rook-ceph-agent
  register: rook_agent_exists
  until: rook_agent_exists is succeeded
  retries: 60
  delay: 5

- name: Ensure rook agents have started
  command: kubectl -n rook-system rollout status daemonset rook-ceph-agent

- name: Wait for rook discover daemonset to exist
  command: kubectl -n rook-system get daemonset rook-discover
  register: rook_discover_exists
  until: rook_discover_exists is succeeded
  retries: 60
  delay: 5

- name: Ensure rook discover has started
  command: kubectl -n rook-system rollout status daemonset rook-discover

- name: Make manifests directory
  tempfile:
    state: directory
  register: rook_manifests_dir

- name: Copy cluster manifests
  template:
    src: "{{ item }}"
    dest: "{{ rook_manifests_dir.path }}/{{ item }}"
  with_items:
    - cluster.yaml
    - storageclass.yaml

- name: Create cluster resource
  command: kubectl apply -f {{ rook_manifests_dir.path }}/cluster.yaml

- name: Wait for cluster pods to become ready
  shell: |
    set -o pipefail
    # Wait until there is at least one pod with the correct label
    until kubectl -n rook-ceph get pod -l app={{ item }} -o json | jq -e '.items|length > 0'
    do
      sleep 1
    done
    # Then wait for them to go into the ready state
    kubectl -n rook-ceph wait --for condition=ready pod -l app={{ item }} --timeout 300s
  with_items:
    - rook-ceph-mgr
    - rook-ceph-mon
    - rook-ceph-osd

- name: Install default-block storage class
  command: kubectl apply -f {{ rook_manifests_dir.path }}/storageclass.yaml
