apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: default-cluster
  namespace: rook-cluster
spec:
  dataDirHostPath: /var/lib/rook
  # Ensure that cluster pods only run on nodes tagged for storage
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: storage-node
                  operator: In
                  values:
                    - rook
  storage:
    useAllNodes: true
    useAllDevices: false
    storeConfig:
      storeType: bluestore
      databaseSizeMB: 1024
      journalSizeMB: 1024
