nodeSelector:
  storage: rook

tolerations:
  - key: storage
    operator: Exists
    effect: NoSchedule

agent:
  toleration: NoSchedule
  tolerationKey: storage

discover:
  toleration: NoSchedule
  tolerationKey: storage
