apiVersion: ceph.rook.io/v1beta1
kind: Pool
metadata:
  name: replica-pool
  namespace: rook-ceph
spec:
  replicated:
    size: 3
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    # Make this the default storage class
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: rook.io/block
parameters:
  pool: replica-pool
  clusterNamespace: rook-ceph
