---

# Restart kubelet due to this bug - https://github.com/kubernetes/kubernetes/issues/68270
- name: Restart kubelet
  service:
    name: kubelet
    state: restarted

- name: Create OpenStack config file
  template:
    src: templates/openstack-config
    dest: /etc/kubernetes/cloud-config

- name: Create/update configmap for OpenStack config
  shell: |
    set -eo pipefail
    kubectl -n kube-system create configmap cloud-config \
      --from-file=/etc/kubernetes/cloud-config -o yaml --dry-run | \
      kubectl apply -f -

- name: Install OpenStack cloud controller manager manifest
  copy:
    src: files/openstack-cloud-controller-manager-pod.yaml
    dest: /etc/kubernetes

- name: Install/upgrade OpenStack cloud controller manager
  command: kubectl apply -f /etc/kubernetes/openstack-cloud-controller-manager-pod.yaml

- name: Ensure OpenStack cloud controller manager has started
  shell: >
    # First, wait for the pod to appear
    until kubectl -n kube-system get pod openstack-cloud-controller-manager
    do
      sleep 1
    done
    # Then wait for it to become ready
    kubectl -n kube-system wait --for condition=ready --timeout -1s pod openstack-cloud-controller-manager
